/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaidRouteImport } from './routes/paid'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'

const PaidRoute = PaidRouteImport.update({
  id: '/paid',
  path: '/paid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/paid': typeof PaidRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/paid': typeof PaidRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/paid': typeof PaidRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/paid' | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/paid' | '/api/public/stripe/webhook'
  id: '__root__' | '/' | '/paid' | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaidRoute: typeof PaidRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paid': {
      id: '/paid'
      path: '/paid'
      fullPath: '/paid'
      preLoaderRoute: typeof PaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaidRoute: PaidRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
